[package]
name = "aoc-2016"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
itertools = "0.12.0"
md-5 = "0.10.6"
regex = "1.10.2"
